### ISSUE TITLE
Change organizational policy members from public to private

### ISSUE THREAD

**Issue by aalferez123** [GoogleCloudPlatform/click-to-deploy-solutions#83]
Hi @sylvioneto !
On data-analytics-platform-event-driven/terraform/function.tf the members allowed is set to AllUsers. Can we change it to a specific principal in order to mitigate security risks? This way Cloud run invocation is not open to the public. It is also preventing us to run it directly on Argolis without modifiying it due to Organizational Policies.

`resource "google_cloud_run_service_iam_member" "run_service_member" {
  location = data.google_cloud_run_service.run_service.location
  service  = data.google_cloud_run_service.run_service.name
  role     = "roles/run.invoker"
  **member   = "allUsers"**`

**Comment by rajasnathak** [comment]
Fixed
